travis:
  secure:
    BINSTAR_TOKEN: C980pyzoRy7s8BFQ0aC9UkZIaNM7/fjpR5T1ER9ajWG9qsiL4q+742TWglV23t6Hb0iaey0tQQK14a9GJR1m1w7Ry36RQYAc2gEXUEi0NZSa2YrabSCzAxwvyiAq9x5TBnnyo3i4kCuIjjiH1crDWbSMv70Q0werRyEWXN8hBHHK3AD5aHGt5+wP11SKLzo0mMj+UFNW8ZymU/lVLWkXTUujmPMDFIZeSaj6/vkLPYBPpmXY8M2SLRzK2hK5b0bElCY+kG82QOAgneQModIzIEXtOcEXaGXnWT0tntU4J/SEkOgfoPzaQiOKaS6vEtTVOBNEaCRF4wY9KgtB3eScS9PfR/6UiMaq7V1kdY+Lb8e+0DGJJO6o2ak/uV/u6ZwhW4/BpONU/UUgFmOWDaoH5Sj+/GCqQQ8pPUNy5TSu7hh915e40uQR9kVgWgIH8pSM2kVw0VhSeQD64Ub+HswVBxKJ9MIe1AUDDrpyHKM/3MgzNkRor2obobHcZFYultTdD3jiYY2eUsQalYbhvlClEaDmbIvnIpkOOUnlZbfsU2RKgCfLY10BPFL9RgHM6B6LeU4GoAHFKKyL/nwXi2pByCFJOYkdAjo4edcpHDszs/Izzeb/TwtXtEY2hVvhdCAhbsmmyXWZfSuebvyntqcBf8Wc+4PiMT5MVVIrYDFj8sY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
